### PR TITLE
Commented Danger rules

### PR DESCRIPTION
**Pull request by piv199**
Temporary removed some danger rules, we should keep improving them onto danger branch. Once they are configured add them to master.

### CODE REVIEW

**Comment by lfarah** [comment]
@goktugyil?

**Comment by goktugyil** [comment]
@lfarah  yep? 

Why is this PR a merge of a lot of PRs?

**Comment by piv199** [comment]
@goktugyil because our master branch contains merge commits, I was rebasing on master branch

**Comment by piv199** [comment]
@goktugyil we need pullrequest template, so we won't apply rules if user inform what he did is fails rules but he aware of it

**Comment by lfarah** [comment]
@piv199 #276

**Pull request closed without merging**
