### PR TITLE
Uilabel changes

### PR DESCRIPTION
**Pull request by vilapuigvila**
## Checklist

- [ ] New Extension
- [ ] New Test
- [ ] Changed more than one extension, but all changes are related
- [x] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @vilapuigvila, can you please explain your changes?

**Comment by vilapuigvila** [comment]
Glups... I'm sorry. Maybe I should not have done that without first consulting. Anyway my idea was to remove animate param bool, becasuse I think is unnecessary if you give a 0 value in duration param. This way we saved to enter a parameter, we can write this label.animateText("text", duration: 0) instead label.setText("", animated: false, duration: 0)

**Comment by lfarah** [comment]
@vilapuigvila makes total sense on the boolean.
Before approving the PR, I just need a couple things from you:
* Put the ```cachesDirectoryPath()``` and ```documentsDirectoryPath()``` in another PR
* Change the method name to ```label.set(text: "text", duration: 0)``` so we're following Swift 3 naming
* Update ```UILabelTests.swift``` with the new method name

**Comment by piv199** [comment]
Please reverse hunk in UIDevice extension

**Comment by Khalian** [comment]
Closing this CR and opening this instead : https://github.com/goktugyil/EZSwiftExtensions/pull/340

**Pull request closed without merging**
