### PR TITLE
<Description> : Adding a new array extension that returns only the unique elements in the array.

### PR DESCRIPTION
**Pull request by Khalian**
<Type> : feature/test

### CODE REVIEW

**Comment by lfarah** [comment]
Don't know why these NSURL Tests failed...
Really good idea for extension! I've used that last month on a small project and it would've been really handy if I had this

**Comment by piv199** [comment]
@Khalian is this faster than `Array(Set(self))`?

**Comment by Khalian** [comment]
I dont know, I did not benchmark it. In theory this should avoid the space complexity of the set, which is O(n). 

But honestly I do not know if Set(self) would actually do the same operation (a contains in the array before putting it into the set). So I cant make any theoretical justifications of time complexity. 

I admit though the Array(Set(self)) is much cleaner.

**Comment by piv199** [comment]
@Khalian My approach is bad because it's not stable.

**Comment by Khalian** [comment]
Is it not reasonable to admit an array element be hashable? Otherwise every contains call would become O(n).

**Pull request merged**
