### PR TITLE
-added HEX initializers for UIColor

### PR DESCRIPTION
**Pull request by zuziakaxel**
I've added two initializers for UIColor. Updated readme.

### CODE REVIEW

**Comment by goktugyil** [comment]
"This branch has conflicts that must be resolved"

Hello, thanks for the pull request. Can you refork and add your commits to the pull request? Or send readme and .swift changes separately?

Thanks

**Comment by goktugyil** [comment]
Hello Alex, can you solve the conflicts?

**Comment by zuziakaxel** [comment]
Yeah sure, I'll do it tomorrow. 😀

**Comment by goktugyil** [comment]
Did you have a chance to look at this Alex?

**Comment by zuziakaxel** [comment]
I need to create new PR with this changes. Closing..

**Pull request closed without merging**
