### PR TITLE
Add necessary changes to compile with Swift2.3

### PR DESCRIPTION
**Pull request by pixel4**
Hey... doing the request to the right branch now. ;)

Thanks

### CODE REVIEW

**Comment by pixel4** [comment]
not sure if travis will complete because Xcode 8 beta.. I saw it failed in the other pull request. But you can verify by running and building with Xcode 8 beta 6

**Comment by goktugyil** [comment]
I'm not running Xcode 8, @lfarah if you are check this out

**Comment by lfarah** [comment]
@goktugyil everything works fine here

**Comment by goktugyil** [comment]
I hope it works, can't test it but it looks ok

**Pull request merged**
