### PR TITLE
Updated travis.ci

### PR DESCRIPTION
**Pull request by lfarah**
Brought to you by @Morbix

### CODE REVIEW

**Comment by lfarah** [comment]
#130

**Comment by Morbix** [comment]
`testFileFunctions` test failed now.

**Comment by goktugyil** [comment]
Its very unintuitive. But if it works then wth

**Comment by Morbix** [comment]
You shouldn't merged this, because still not working. 1 test is failing yet.

**Comment by lfarah** [comment]
@Morbix I think it's ok to merge this if the test fails. Now I'll work on fixing that test 😉

**Comment by Morbix** [comment]
Nice!

**Pull request merged**
