### PR TITLE
Added makeCircular() to UIViewExtensions

### PR DESCRIPTION
**Pull request by lfarah**

### CODE REVIEW

**Comment by goktugyil** [comment]
There was a func which does this

**Comment by lfarah** [comment]
@goktugyil there's an extension for UIImageView called roundSquareImage(), but in UIView would be much better, so not only images can be rounded

**Comment by goktugyil** [comment]
why do you need to set the center?

**Comment by lfarah** [comment]
You don't, sorry. I found that method in the internet and someone added the center

**Comment by lfarah** [comment]
I changed

**Pull request merged**
