### PR TITLE
New README [WIP]

### LINKED ISSUE #268: README Cleanup
I think it's time for us to rewrite our `README.md`, because it is too big and confusing.

I think this is a big thing and it's open for discussion.

My idea:
- Do a **simple** README like [this one](https://github.com/lfarah/awesome-iOS-contributions/blob/master/README.md), with the most common extensions (like Dictionary, array and String)
- For more documentation, ask the user to [Go to our CocoaDocs](http://cocoadocs.org/docsets/EZSwiftExtensions/1.7/)

What do you guys think?
# Examples
- Sending feedback email by getting device information
- Having a countdown timer with `Timer.runThisEvery()`

### PR DESCRIPTION
**Pull request by lfarah**
## Checklist

- [ ] New Extension
- [ ] New Test
- [ ] Changed more than one extension, but all changes are related
- [x] Trivial change (doesn't require changelog)

fixes #268 and #307 and #289 and #100

### CODE REVIEW

**Comment by lfarah** [comment]
What do you think, @goktugyil?

**Comment by goktugyil** [comment]
- Maybe change Usage to Example Usage
- Easily get an object at a specified index: // I think there are better examples out there, or at least should show that it could return nil. 

Looking good, but need to add link to old examples, if the user wants detailed examples

**Comment by lfarah** [comment]
@goktugyil: http://cocoadocs.org/docsets/EZSwiftExtensions/

**Comment by goktugyil** [comment]
I think thats going to change with the new version

**Comment by lfarah** [comment]
@Khalian what do you think? I'd like your input as well as @piv199 and @vilapuigvila's since that's an important decision

**Comment by Khalian** [comment]
Yea its pretty good. We might want to take down the CGRect example (its not that commonly used).

**Comment by Khalian** [comment]
Looks good now, you might want to squash your 5 commits to one (it isnt adding any extra information).

**Pull request merged**
