### PR TITLE
Macos support for EZSwiftExtensions. 

### PR DESCRIPTION
**Pull request by Khalian**
## Checklist

- [ ] New Extension
- [ ] New Test
- [x] Changed more than one extension, but all changes are related
- [x] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by Khalian** [comment]
@goktugyil - I want to put this change in before I draft the new release. I would appreciate your review for this one, since this is a massive change.

**Comment by goktugyil** [comment]
Code looks good, but I'm worried about the proj and scheme files. Usually you can't catch issues in those without stumbling into it while using :/

**Comment by goktugyil** [comment]
Lets just not make a version for a while, gives us time to catch stuff.

**Comment by goktugyil** [comment]
Also why not use 
`#if !os(macOS)`
?

**Comment by Khalian** [comment]
@goktugyil I agree. I can guarantee you the following.

1. The build works fine. 
2. The target builds fine locally on my XCode. 
3. The tests run fine locally on my XCode. 

How about I keep these changes for a couple of weeks or so? After that I can merge them. 

Regardng !os(macOS), I also have to make changes for linux and maybe watchOS depending on demand. In linux, UI Kit is not defined, so this change is good.

**Pull request merged**
