### PR TITLE
<Description> : Adding the dot product operation for the vector representation of CGPoints.

### PR DESCRIPTION
**Pull request by Khalian**
## Checklist

- [x] New Extension
- [x] New Test
- [ ] Changed more than one extension, but all changes are related
- [ ] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by goktugyil** [comment]
I think we shouldn't a new operator for this. After all we're not a graphics library and if a person wants to do this with their custom operator, they easily can. I think the name should be intuitive and readable like all functions.

**Comment by lfarah** [comment]
@goktugyil can we close this?

**Comment by Khalian** [comment]
In that case should I refactor this to func dotProd instead of the operator?

**Comment by lfarah** [comment]
@piv199? @goktugyil?

**Comment by goktugyil** [comment]
@Khalian  yes like this

**Pull request merged**
