### PR TITLE
Add Carthage Support

### LINKED ISSUE #6: Carthage Support?
Im really excited for this repo, but I am wondering if there will be Carthage support anytime soon?

### PR DESCRIPTION
**Pull request by bcylin**
I've replace the current single view application with an iOS framework project. If the example app is needed, it could be organised in a workspace alongside the framework.

Please bump another version and create a tag after this pull request, otherwise a branch name should be specified in the `Cartfile`. There are some deprecation warnings that I haven't looked into yet. I think they could also be taken care of later.

For now, a `Cartfile` as follows should work:
```
github "bcylin/EZSwiftExtensions" "feature/framework"
```

This should close #6. Please try this out, thanks.

### CODE REVIEW

**Comment by goktugyil** [comment]
Thanks for to update!
We need people to be able to download the project and just compile and test its features. Thats the reason for the example app, can you bring that back please?
Also this update won't be messing with the current cocoapods correct?

**Comment by bcylin** [comment]
Sure I will bring back the example app. The `Sources` and `EZSwiftExtensions.podspec` stay unchanged so this won't affect CocoaPods.

**Comment by bcylin** [comment]
I rearranged my commits and renamed the example app to `EZSwiftExtensionsExample`.

**Comment by goktugyil** [comment]
Thanks. Does there have to be 2 xcodeproj's ?

**Comment by bcylin** [comment]
Yes there are two xcodeprojs and one xcworkspace.

```
EZSwiftExtensions.xcworkspace
├─ EZSwiftExtensions.xcodeproj
└─ EZSwiftExtensionsExample.xcodeproj
```

It'll look like this: https://github.com/bcylin/EZSwiftExtensions/tree/feature/framework

Please try this workspace on your machine and see if it works as expected, thanks!

```
git clone git@github.com:bcylin/EZSwiftExtensions.git tmp --branch feature/framework --origin bcylin && cd tmp
```

**Comment by goktugyil** [comment]
It works, need to make a little edit tho. 
Thanks bro :+1:

**Comment by bcylin** [comment]
:beers:

**Pull request merged**
