### PR TITLE
<Description> : Removing foreach since it conflicts with the std libr…

### PR DESCRIPTION
**Pull request by Khalian**
…ary.

<Type> : fix

## Checklist

- [ ] New Extension
- [ ] New Test
- [ ] Changed more than one extension, but all changes are related
- [x] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by Khalian** [comment]
Done.

**Comment by DanielAsher** [comment]
Hi, 
I believe that removal of https://github.com/goktugyil/EZSwiftExtensions/blob/928d825dcc5002f468d8cfc0b94b98a5910f160c/Sources/ArrayExtensions.swift#L135 is required for correctly implementing this PR

**Comment by Khalian** [comment]
That method is not deprecated, and we need to think this through if we do want to deprecate it.

**Comment by DanielAsher** [comment]
@Khalian: thanks for this info. I'll go ahead and fork. Probably for the best :) I'd be glad to start making the minor changes for protocol based extensions on concrete types there.

**Comment by Khalian** [comment]
@lfarah @goktugyil Can we deprecate the method that @DanielAsher mentioned : https://github.com/goktugyil/EZSwiftExtensions/blob/928d825dcc5002f468d8cfc0b94b98a5910f160c/Sources/ArrayExtensions.swift#L135 . If so I can put out a minor release adding this to something like 1.9.1.

**Comment by Khalian** [comment]
@DanielAsher As for unblocking you, I will quickly discuss with the other maintainers and maybe put out a minor version. Sorry for the inconvenience.

**Comment by DanielAsher** [comment]
@Khalian thanks so much for your attention to this. maintaining a well-used library has many complexities - best of luck and wishes for the future!

**Comment by goktugyil** [comment]
@Khalian Why are we deprecating it again?

**Pull request merged**
