### PR TITLE
<Description> : Adding day, month and year extensions to date.

### PR DESCRIPTION
**Pull request by Khalian**
## Checklist

- [x] New Extension
- [x] New Test
- [ ] Changed more than one extension, but all changes are related
- [ ] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by lfarah** [comment]
@Khalian do you wanna also add the **month*  as String? Also index + String of the current day of the week would be good.
``` swift
    // EZSE : Get the weekday from the date
     public var week: String {
		let dateFormatter = NSDateFormatter()
		dateFormatter.dateFormat = "EEEE"
		return dateFormatter.stringFromDate(self)
    }

**Comment by Khalian** [comment]
Ok, I can put the week in. 

I dont understand why the month should be string? The gregorian calendar has different syntax across different cultures. An integer makes more sense as it disambiguates.

**Comment by goktugyil** [comment]
I think month makes more sense as int too. But there might be some use cases for string, idk.

**Comment by lfarah** [comment]
I think we should have both **Int** and **String** for *month* and *day of the week*

**Comment by goktugyil** [comment]
Wouldn't hurt I guess

**Comment by Khalian** [comment]
No I dont understand how I am going to implement a string based month here. 

Will it be locale specific (e.g. for spanish have a struct with all of the months and return it accordingly), similarly for english and so on.

**Comment by lfarah** [comment]
@Khalian ```NSDateFormatter``` gives us the month name in the right locale:
``` swift
extension NSDate {
    var month: String {
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "MMMM"
        return dateFormatter.stringFromDate(self)
    }
}
```

**Comment by Khalian** [comment]
Added weekday and monthAsString.

**Comment by lfarah** [comment]
Thanks @Khalian! 👍 
Can you please remove the changes on ```CGPointExtensions.swift```,```UITextFieldTests.swift``` and ```CGPointTests.swift```?

**Pull request closed without merging**
