### PR TITLE
Add Dictionary test cases for the new extensions

### PR DESCRIPTION
**Pull request by pixel4**
Hey man,

I just added test cases for the new extensions on Dictionary

### CODE REVIEW

**Comment by pixel4** [comment]
I think after this one, if everything looks okay, we should also bump the version again to `1.2.3` to we have an stable version available with all latest added extensions. Specially after making those method public again on the Array stuff.

**Comment by goktugyil** [comment]
Thanks for the commit, I'll bump the version up now. 

Can you edit the readme sometime to reflect your additions too?

**Comment by nchodelski** [comment]
Hi,

I'm actually already working on the array & dictionary readme examples.
I'll submit a pull request tomorrow.

Natalia / nchodelski on github

**Comment by pixel4** [comment]
Hi @nchodelski,

that's awesome, thank you for the help : )

**Comment by goktugyil** [comment]
Awesome :+1:

**Pull request merged**
