### PR TITLE
<Description> : Migrating serialization and deserialization of JSON to Dictionary from NSDictionary

### PR DESCRIPTION
**Pull request by Khalian**
## Checklist

- [x] New Extension
- [x] New Test
- [x] Changed more than one extension, but all changes are related
- [ ] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by Khalian** [comment]
https://github.com/goktugyil/EZSwiftExtensions/issues/334

**Comment by lfarah** [comment]
@Khalian can you solve the conflicts?

**Comment by lfarah** [comment]
Actually, I just did using the new Github merge conflict tool

**Comment by Khalian** [comment]
I resolved the conflicts.

**Pull request merged**
