### PR TITLE
Added UnitTests + Added Size Classes + Bug Fixes

### PR DESCRIPTION
**Pull request by valeIT**
**Note:** I feel like 3 different commits for all the different areas changed is better, but if you prefer just one commit for everything that's fine too. Just let me know.

I've added test cases for most of the project and changed a few things (listed below), it's just one commit for now, let me know if you'd prefer to have one commit for the tests and one for the rest.

It's pretty large change to I'm open to discussions / rolling back a few things if you feel like they're out of place.

#UnitTests

I've written the UnitTests for most of the extensions, there are still a few missing but let's say 80/90% done.

Added for:
- Dictionary
- Int
- NSDate
- String
- Array
- BlockButton
- Bool
- CGFloat

#Changes

##NSDate

I've added an API for specifying your own format for  `dateFromString`, same deal for `toStringUsingFormat`. Added the operator `>` and fixed the `==` to use the NSDate specific `isEqualTo`.

##NSObject

Swift [recently added](https://www.natashatherobot.com/nsstringfromclass-in-swift/) `String(className)` to the language so we don't need to use the bridging for that anymore.

##String

Trimming didn't work, changed it to [this](http://stackoverflow.com/questions/5581141/stringbytrimmingcharactersinset-is-not-removing-characters-in-the-middle-of-the/26152034#26152034) and added a non mutating function as well to do the same.

##ez Struct

Added `verticalSizeClass` and `horizontalSizeClass` for the top ViewController (defaults to Unspecified if it's not set yet). Also added a `.stringValue` to `UIUserInterfaceSizeClass` for easier comprehension and debugging.

### CODE REVIEW

**Comment by goktugyil** [comment]
Whoa lots of cool additions! Thanks for the PR. 

Its always better to send these types of pull requests one by one. Its fine this time, but I am attending GGJ and I want to check these sometime later before merging. 

I hope thats ok and you don't need pod update right away

**Comment by valeIT** [comment]
Sure, if you need them one by one don't worry you can close and I'll reopen (just say it). 

And sure, take your time, no hurries at all. =)

**Comment by goktugyil** [comment]
Hello @valeIT  

I'm sorry for so late reply. The branch has conflicts, can you fix them so I can merge? Thanks!

**Comment by valeIT** [comment]
Done and nw =)

**Comment by goktugyil** [comment]
Thanks :+1:

**Comment by goktugyil** [comment]
Can you document the code, especially the CGFloat and horizontalSizeClass ones? Cause they are not very clear

https://github.com/goktugyil/EZSwiftExtensions/issues/19

**Pull request merged**
