### PR TITLE
Adding support for checking if app is running in testflight mode.

### PR DESCRIPTION
**Pull request by Khalian**
## Checklist

- [x] New Extension
- [ ] New Test
- [ ] Changed more than one extension, but all changes are related
- [ ] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by Khalian** [comment]
@goktugyil  Would you mind taking a look at this ?

**Comment by goktugyil** [comment]
You want me to test this inside my app while its in test flight?

**Comment by Khalian** [comment]
Yes, I am not actively writing an App at this time and some friends have asked for this. So that would be helpful.

Also, approving it so that I can merge it.

**Comment by goktugyil** [comment]
I'll check this when I send a TestFlight version, probably 1-2 weeks later.

**Comment by goktugyil** [comment]
Tested this on TestFlight, and returns true as expected.
Tested in normal install, and return false.
Haven't tested on live app, is that test also needed?

**Comment by Khalian** [comment]
@goktugyil No, that should be good enough.

**Pull request merged**
