### PR TITLE
added #if blocks around ios specific stuff, to allow for support of tvos

### PR DESCRIPTION
**Pull request by alkalin3**
This will allow EZSwiftExtensions to support tvos. 

Tvos is mostly the same minus some iphone/ipad specific things.

I didn't increment the pod version but, it is probably something to consider.

### CODE REVIEW

**Comment by goktugyil** [comment]
Thanks for the pull request :+1:

**Comment by alkalin3** [comment]
No problem. Want me to follow up with a version increment on the cocoapod?

**Comment by goktugyil** [comment]
I want to test the pull requests and push a few commits on my own before the next pod update. Do you need the update urgently?

**Comment by alkalin3** [comment]
Nope. I can wait.

**Comment by goktugyil** [comment]
Hi, I made a new version

**Comment by goktugyil** [comment]
Hey man, I had to revert that addition cause it didn't work as a framework when installed with cocoapods. you can try the version 1.0.4, it doesn't compile on ios devices. It works fine on the example project btw. I don't know the reason but if you can solve it or find a workaround for it, that would be great.

https://github.com/goktugyil/EZSwiftExtensions/commit/be84d7a998461830867d52e20d8e14f30f2eb0c5

**Comment by alkalin3** [comment]
I'll take a look at it tomorrow.

**Comment by PatrickSCLin** [comment]
no plans for tvOS ?

**Comment by goktugyil** [comment]
If you guys can get it to work then why not

**Pull request merged**
