### PR TITLE
Class fun to print family fonts and font names

### PR DESCRIPTION
**Pull request by vilapuigvila**
## Checklist

- [ ] New Extension
- [ ] New Test
- [x] Changed more than one extension, but all changes are related
- [x] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by piv199** [comment]
I can't see a good use case for this method, because when it's printed it doesn't reflect the style. And if you would like to know all family fonts you could refer to http://iosfonts.com .

**Comment by vilapuigvila** [comment]
@piv199 I used to print fonts when I added extra fonts in xcode, sometimes font name doesn't match with the print name, and then I waste time to get font.. I didn't know http://iosfonts.com , great website!!

**Comment by Khalian** [comment]
I am more bothered about how to test this. Can you confirm that this print method does has have different output across swift versions or devices?

**Comment by lfarah** [comment]
We already deprecated [that function](https://github.com/goktugyil/EZSwiftExtensions/blob/master/Sources/UIFontExtensions.swift#L97)

**Comment by Khalian** [comment]
Hey would it make sense to include static methods for all the font families (getters using CGFloat)? Or is it overkill ?

**Comment by lfarah** [comment]
@Khalian I think it's overkill

**Comment by vilapuigvila** [comment]
right, so you can close this PR. Thanks

**Pull request closed without merging**
