### PR TITLE
Attempting to fix build.

### PR DESCRIPTION
**Pull request by Khalian**
## Checklist

- [ ] New Extension
- [ ] New Test
- [ ] Changed more than one extension, but all changes are related
- [x] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by lfarah** [comment]
Hmmm travis failed. What's happening?

**Comment by Khalian** [comment]
@lfarah Yea this was to debug the issue. 

The command "xcodebuild clean build test --verbose -project "$PROJECT" -scheme EZSwiftExtensions-macOS -destination 'platform=macOS,arch=x86_64' | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-macos.json" xcpretty -f `xcpretty-json-formatter`" exited with 64.
11.37s$ pod lib lint
 -> EZSwiftExtensions (1.11)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

This is freaking weird, i specifically put in verbose flag there.

**Comment by Khalian** [comment]
Ok I made a mistake before. This is the real reason why its failing.

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild. 
xcodebuild clean build -workspace /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/CocoaPods-Lint-20171004-12552-wds503-EZSwiftExtensions/App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY=
Build settings from command line:
    CODE_SIGN_IDENTITY = 
=== CLEAN TARGET EZSwiftExtensions OF PROJECT Pods WITH CONFIGURATION Release ===
Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
** CLEAN FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET EZSwiftExtensions OF PROJECT Pods WITH CONFIGURATION Release ===
Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
** BUILD FAILED **

@lfarah Have you seen any issue like this before. This does not look to be an explicit command in travis yml.

**Comment by Khalian** [comment]
I verified that the SWIFT_VERSION flag is indeed defined in the pbxproj file. 

I am kind of at a loss for why this is happening. @goktugyil @lfarah any tips?

**Pull request closed without merging**
