### PR TITLE
fixed bug setting image on undefined thread for `imageWithURL` related methods

### PR DESCRIPTION
**Pull request by piv199**
Also Removed code duplicate

#217

### CODE REVIEW

**Comment by lfarah** [comment]
Hmmmm, I read the method ```imageWithUrl(url:)``` and I'm thinking about how this naming can be better in Swift 3. Maybe do an initializer like ```UIImageView(url: String)```

What are your thoughts?

**Comment by piv199** [comment]
@lfarah looks awesome, but what's about supporting storyboards?

**Comment by lfarah** [comment]
I didn't see any @IBDesignable or @IBInspectable... How is this extension supporting storyboards?

**Comment by piv199** [comment]
@lfarah imagine you set up storyboard view controller with view and UIImageView on it, then you set reference to this UIImageView in your ViewController class. Once ViewController viewDidLoad you would like to load an image into UIImageView from url.

You cannot reassign `UIImageView` with `UIImageView(url: String)`, but you can do `imageView.imageWithURL(...)`

**Comment by lfarah** [comment]
Alright. Now I understood what you meant by "supporting storyboards".
What if we add this initializer and also change the name to something like:```imageView.image(urlString:...)```, so it looks more like Swift 3

**Comment by piv199** [comment]
@lfarah yes it makes sense, also I think there are should be support for urlString and url. About naming, yes, I haven't changed this file yet

**Comment by piv199** [comment]
@lfarah this is just hot fix, naming is about another pull request, also adding new features is out of scope current pr

**Pull request merged**
