### PR TITLE
New algorithm for UIImage Extension methods

### PR DESCRIPTION
**Pull request by Yu-w**
Using `UIBezierPath` to `addClip` UIImage to have roundedCorner is better than simple setting corner radius in two ways:
1. Avoiding side effects of setting additional `clipToBounds`
2. Avoiding offscreen rendering; useful when displaying a bunch rounded images

New class explicit for image downloading; a lot efficient and thread-safe than simple url request.

### CODE REVIEW

**Comment by piv199** [comment]
roundSquareImage it's really cool! Could we parameterize it with level of corning?

**Comment by Yu-w** [comment]
Yeah, maybe another pull request later

**Comment by goktugyil** [comment]
What kind of test cases would be appropriate for this?

**Comment by Yu-w** [comment]
To be honest, have no idea how to test yet... I've used this two in my projects a lot and haven't found a single problem yet.

**Comment by lfarah** [comment]
@goktugyil can we merge this without tests?
@Yu-w is this working in Swift 3?

**Comment by goktugyil** [comment]
I don't think it will work in Swift3, it has NSURL stuff. 

It also seems to have project reference issues. I can fix that easily after Swift3 problems are fixed.

**Comment by lfarah** [comment]
Guys, now we can work on this since 3.0 was approved

**Pull request closed without merging**
