### PR TITLE
<Description> : Adding integer to digitArray conversion.

### PR DESCRIPTION
**Pull request by Khalian**
<Type> : feature/test

## Checklist

- [x] New Extension
- [x] New Test
- [ ] Changed more than one extension, but all changes are related
- [ ] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by lfarah** [comment]
How is this extension relevant? @Khalian did you use it in any project?

**Comment by Khalian** [comment]
In our work. I had to iterate over digits for different purposes.

**Comment by piv199** [comment]
This is very specific extension, that would not be used widely...

**Comment by goktugyil** [comment]
What kind of different purposes?

**Comment by Khalian** [comment]
I had to compute the digital sum for some checksum algo

**Comment by Khalian** [comment]
You can acquire the nth digit in O(1) time

**Pull request merged**
