### PR TITLE
Add a bunch of function to NSDate Extension

### PR DESCRIPTION
**Pull request by Yu-w**
Function added:
`timePassedShort`
`dateFromTimestampString`
`getYear`
`getMonth`
`getDay`
`getAstro`
`noticeTime`

### CODE REVIEW

**Comment by goktugyil** [comment]
/// EZSE: Check date if it is yesterday
public func isDateYestoday() -> Bool 

small typo

**Comment by Yu-w** [comment]
Nice catch man

**Comment by piv199** [comment]
Is there any way I could push into this pull requests, or I need to create a separate pull request?

http://stackoverflow.com/questions/13324633/nsdate-beginning-of-day-and-end-of-day

- [ ] startOfDay
- [ ] endOfDay

I was recently using that extension and it's cool. But maybe add for month, year same properties.

**Comment by Yu-w** [comment]
Added you as a collaborator for my repo: https://github.com/Yu-w/EZSwiftExtensions

**Comment by piv199** [comment]
Also, It's not a swift style of creating `getYear` for example. We should treat such things as properties.

Like, `NSDate().year` and not `NSDate().getYear()`. The second is like Java-style.

**Comment by Yu-w** [comment]
Any update in `date` branch will be shown to this pull request. XD

**Comment by Yu-w** [comment]
Agree. Properties feel better.

**Comment by piv199** [comment]
Also swiftlint tells `timePassedShort` cyclomatic complexity.

timePassed, timePassedShort, noticeTime, getAstro - what about localizations?

**Comment by Yu-w** [comment]
Hmmm, actually, I am not quiet familiar with NSDate localization. Would you mind to fix the localization issue?

**Comment by piv199** [comment]
@Yu-w , I'm saying that you are returning English hardcoded strings, and not localization-dependant. Like `Yesterday, ago, Argo and so on`.

I don't actually know if localization is the same as we use in app.

Also, please check if its valid for macOS.

**Comment by Yu-w** [comment]
Well, it seems that we need a content strategist and/or a translator~

**Comment by Yu-w** [comment]
I think we don't have to worry a lot about localization for now; maybe improve later~

**Comment by piv199** [comment]
@Yu-w , yes you are right, but not to forget :)

So for now - tests, properties instead functions

@goktugyil also what do you think about this pull request. What should we do for this pull request?

**Comment by Yu-w** [comment]
@piv199 And for **cyclomatic complexity**, it's just because there are too many `if` statements in that function. I think we can safely ignore that linter warning... (or set complexity a bit higher, maybe 15)

**Comment by piv199** [comment]
I'll write tests tomorrow if you don't do this before ;)

**Comment by Yu-w** [comment]
Coooooool! (although it seems we wrote same thing as same time... nvm... fixed)

**Comment by piv199** [comment]
We still need tests for
- [ ] noticeTime
- [ ] timePassed
- [ ] timePassedShort

Also there are some failings with getComponent. It's obviously Apple thinking :).

What is the purpose of `dateFromTimestampString`. Why is it not a faillable initializer? And why don't use `NSDate(timeIntervalSince1970: int)`?

Also, there are some methods that really will be cool something like `dateByAddingDays/Months/Years`. But we need to decide what we want really to have in this library. There are lots of great NSDate extension libraries on github.

**Comment by piv199** [comment]
Hm... I wonder whether we should have init from httpDateString or not. Maybe it's a better to have init with some enum or array of allowed conversions.

I just found that RFC822 have **32** date formats. [See here, the second answer](http://stackoverflow.com/questions/284775/how-do-i-parse-and-convert-datetime-s-to-the-rfc-822-date-time-format)

**Comment by Yu-w** [comment]
I would say we can just leave `httpDateString` as it is for now; let @goktugyil decides in later pull request.

**Comment by goktugyil** [comment]
Are you done with this feature set or is there more work to be done?

**Comment by piv199** [comment]
@goktugyil there could be a lot more features for NSDate, but which of them do we really need and which not.

This branch still doesn't have tests for some added methods.
Also, as for me, `init(httpDateString: String)` is not good enough. it supports not enough rfc/iso patterns(I wrote some in tests, that's why tests are failing).
Another thing is localization, but, perhaps do it in another pull request.

**Comment by Yu-w** [comment]
So how about merge this PR first and then do more improvement on `init(httpDateString: String)` and localization in later pull requests?

**Comment by lfarah** [comment]
@Yu-w, now I'm into EZSwiftExtensions administration so I'll be able to help you with your Pull Request.
I have a couple questions for you:
1. Are your extensions available in Swift 3?
2. Do you have tests?

If you don't have any of those, I can help you do it so we can quickly merge this PR

**Comment by Yu-w** [comment]
1. Haven't rewrite them in Swift 3.
2. All function have valid test except `testFromHttpDateString` which not belong to this PR I think.

Definitely appreciate for any help XD!

**Comment by goktugyil** [comment]
After releasing the first stable version of Swift3 lets work on converting these to Swift3.

**Comment by lfarah** [comment]
Now we can work on this

**Comment by lfarah** [comment]
@Yu-w any updates?

**Comment by goktugyil** [comment]
Maybe working from a clean state might be a good idea for these

**Comment by piv199** [comment]
I can contribute, but this is not in priority list

**Pull request closed without merging**
