### PR TITLE
Some new extensions for String, NSDate, NSURL, NSDictionary, UIApplication, UIImage, Double/Float

### PR DESCRIPTION
**Pull request by amosavian**
For String:
- Base64 encoding/decoding
- Regular expression matching
- Counting words and paragraphs
- Coloring substring
- Get position of substring
- pattern match for hasPrefix() and hasSuffix to use in select-case
- Height of rendered text in view

Double/Float:
- String initializer with precision formatting

NSURL:
- Get file size from remote server and checks if it support resume
- File (local) related function : get size, modification date and creation date
- Checks if path is a directory

NSDate:
- Init NSDate from HTTP response header date

NSDictionary:
- JSON serialization 

UIApplication:
- run a block after app resigns activity in iOS

UIImage:
- colorized pattern from image

### CODE REVIEW

**Comment by goktugyil** [comment]
Thanks for the pull request. These seem like potentially dangerous extensions. Can you add some tests to these additions?

Also +    /// EZSE: Returns remote size of url, don't use it in main thread
Its better to handle threads inside the function, but then there is the return problem. hmm

Also just adding files doesn't work. They have to be referenced in both targets, 

Like this: https://github.com/goktugyil/EZSwiftExtensions/commit/50e2511dfd8246e125516bf3015c107fe8e7a493

The files need to be in the sources folder. I create the files in somewhere else then, add the files in the sources folder from finder. Then drag the new file inside the sources folder to the 2 targets inside the xcode project and place them in the sources folder in there. Copy file prompt is unchecked. I hope this makes sense. @lfarah

**Comment by amosavian** [comment]
hey @goktugyil ,
They are variables with return values. we can replace them with functions with completion handlers in this case. Though that NSLog notification were enough for me, you may decide it's not ideal for general, or replace NSLog with assert. Tell me what you prefer.
About dropping files inside project I created files here and have no clone on my desktop. I will clone and try to update project files and paste them here again

**Comment by goktugyil** [comment]
Well multi thread code is annoying, except when you use ez.runthisinbackground 😁 
Completion handlers seems like a better idea.

**Comment by amosavian** [comment]
hi @goktugyil ,
please check these new commits

**Comment by goktugyil** [comment]
Seems good. All thats missing seems to be tests

**Comment by amosavian** [comment]
@goktugyil now test has been implemented and some minor syntax errors has been fixed

**Comment by goktugyil** [comment]
Now we have merge conflicts :(

**Comment by amosavian** [comment]
How about closing this pull and I create a new one?

**Comment by loveuqian** [comment]
@goktugyil 
want a new extension for image to crop circle image

**Comment by goktugyil** [comment]
@loveuqian what do you mean? There is a UIView.roundSquareImage & .roundCorners

**Pull request closed without merging**
