### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by piv199**
Initial changelog commit
Will do Unreleased part and could be merged

### CODE REVIEW

**Comment by piv199** [comment]
@goktugyil @lfarah @Khalian 

Take a look at template [changelog.md](https://github.com/piv199/EZSwiftExtensions/blob/changelog/CHANGELOG.md)

- Should we change #### to just bold or even just text? Is it readable?
- Should we have a context menu for changelog section?
- Should we add tests change/adding/fixing messages to changelog?
- Should we add Danger/Codecov messages to changelog?
- Maybe change to table instead of list?
- Do we need to specify commit hash/url, author? issue related?

**Comment by lfarah** [comment]
#### Should we change #### to just bold or even just text? Is it readable?
> Perfect the way it is right now
 
#### Should we have a context menu for changelog section?
> I didn't understand

#### Should we add tests change/adding/fixing messages to changelog?
I don't think so

#### Should we add Danger/Codecov messages to changelog?
> I don't think so

#### Maybe change to table instead of list?
> For me list is better

#### Do we need to specify commit hash/url, author? issue related?
> It's good to specify author, other things don't seem that important

**Comment by piv199** [comment]
Updated, should we stick with such changelog?

**Comment by lfarah** [comment]
@piv199 I think it's supposed to be all capital: ```CHANGELOG.md```. Besides that, it's perfect. Really good job! 🎉

**Comment by piv199** [comment]
@lfarah it's already have that name

**Comment by Khalian** [comment]
Should we change #### to just bold or even just text? Is it readable?

It looks all right. The purpose is legibility and #### amply satisfies that. 

Should we have a context menu for changelog section?

I think what you meant is what the change accomplishes (the purpose of a extension etc). In that case yes. Otherwise can you please elaborate?

Should we add tests change/adding/fixing messages to changelog?

No, and the reason I believe that is that the end user/programmers actually do not care about fixes and tests. 

Should we add Danger/Codecov messages to changelog?

No, similar reason as above. 

Maybe change to table instead of list?

The table is more concise. However if we wish to express context then a list is better way to do it. First we must arrive at the decision point whether we wish to include context. 

Do we need to specify commit hash/url, author? issue related?

The author to me is sufficient.

**Comment by piv199** [comment]
Currently ** instead of ####

I ment a menu for section so we could easily jump to submenu "Added extensions" in 1.8. But your idea is interesting too...

I agree about tests, but not fixes in methods. If we fixed method we should add it.

I made renaming/deprecating with table because it's more concise, other is better in list variant.

commit hash maybe makes some sense, so when we look all changes we could easily jump to related pull request?

**Comment by Khalian** [comment]
"I agree about tests, but not fixes in methods. If we fixed method we should add it."

My opinion would be if it modifies user experience then yes we should add. 

"I made renaming/deprecating with table because it's more concise, other is better in list variant."

Yes thats a good reason for using a table. 

"commit hash maybe makes some sense, so when we look all changes we could easily jump to related pull request"

I am not certain if end users will actually care about the commit hash. If they wanted to check the implementation they can directly jump into the source from XCode.

**Comment by lfarah** [comment]
@piv199 can we push this?

**Comment by piv199** [comment]
@lfarah I'l update and we will merge

**Comment by goktugyil** [comment]
> Should we change #### to just bold or even just text? Is it readable?

I think the number would be better if it was bold

**Comment by goktugyil** [comment]
> Should we change #### to just bold or even just text? Is it readable?

I think the number would be better if it was bold

> Should we have a context menu for changelog section?

No need. 

> Should we add tests change/adding/fixing messages to changelog?

Separate tests, irrelevant for the changelog. However something like "Increased test coverage by %4" might be good. 

> Should we add Danger/Codecov messages to changelog?

Messages? Like changes?

> Maybe change to table instead of list?


List

> Do we need to specify commit hash/url, author? issue related?

Lets give credit where its due. Even though github is good at it anyways.

**Comment by piv199** [comment]
@goktugyil Okay, I'll add

**Comment by piv199** [comment]
@lfarah I update as soon as I'm free, possibly tomorrow... so we could merge, and proceed with changelog in every pr.

**Comment by lfarah** [comment]
@piv199 perfect!

**Comment by Khalian** [comment]
Should we squash merge it at this time ?

**Comment by piv199** [comment]
@Khalian yes, i forget how to do it properly

**Comment by Khalian** [comment]
@piv199 rebase -i HEAD~23 on cmd and then replace the the picks with s for the 21 odd commits that you want to squash down. This will replay all the diffs into one big diff. While you do this it also will allow you to change the commit message should you choose to do so. Hope this helps.

**Comment by lfarah** [comment]
@Khalian ?

**Comment by Khalian** [comment]
It looks good minus the fact that there are 25 commits representing a Changelog as I type this.

**Comment by piv199** [comment]
#344

**Pull request closed without merging**
