### PR TITLE
NSDate start/end of day property + tests + readme

### PR DESCRIPTION
**Pull request by piv199**
Work in progress [WIP]

- [X] startOfDay
- [X] endOfDay
- [ ] startOfMonth
- [ ] endOfMonth
- [ ] startOfYear
- [ ] endOfYear

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @piv199, let me know how I can help you with this PR

**Comment by piv199** [comment]
@lfarah Yeah, I could finish it myself with tests, I just forgot about it.

**Comment by piv199** [comment]
Can't run Xcode 8 with master branch. Try to fork again and make a new pull request when establish swift 3.0

**Comment by goktugyil** [comment]
This is the problem with large pull requests 😁  

Better idea would be to plan it out in an issue and send separate pull requests for each little function and test that works.

**Pull request closed without merging**
