### PR TITLE
Travis ci strikes back

### PR DESCRIPTION
**Pull request by piv199**
xcodebuild instead of xctool
Two schemes: iOS and tvOS
Also added pod lint

### CODE REVIEW

**Comment by piv199** [comment]
Travis not strikes back, still need to fix iOS scheme, tvOS testing is working

**Comment by lfarah** [comment]
Damn.... do you even sleep? hahahahah

**Comment by piv199** [comment]
@lfarah yes, I'll create a new pull request that more accurate shows my changes to start work travis.
Now it really seems to do what it should, also codecov is working 👍

**Comment by lfarah** [comment]
#221 is a little bit harder but I'll try to do it over the weekend

**Pull request closed without merging**
