### PR TITLE
Add text change animation to labels. Fix issue #17

### PR DESCRIPTION
**Pull request by avismarahl**

### CODE REVIEW

**Comment by goktugyil** [comment]
/EZSwiftExtensions-master/Sources/UILabelExtensions.swift:62:55: Use of unresolved identifier 'GlobalConstants'

**Comment by avismarahl** [comment]
Oh wait. A commit coming up soon. -_-

**Comment by avismarahl** [comment]
Done. You can merge it if you want to.

**Comment by goktugyil** [comment]
Fix issue #17 is not working when I use 

        let arr = [1,2,3,4]
        let arr2 = [1,2,3]

**Comment by avismarahl** [comment]
I think it does. 
screen shot 2015-12-28 at 12 12 44 pm

**Comment by goktugyil** [comment]
Oh yeah, my bad.

**Comment by goktugyil** [comment]
I pushed all your updates to the new version. 

https://github.com/goktugyil/EZSwiftExtensions/commit/b67b0e17a40515ce5ccc1fc0861f16017e5290df

Btw we need to specify each func with public or it doesn't work as a framework

**Pull request merged**
