### PR TITLE
<Description> : Adding vector and angle based constructors for CGPoint.

### PR DESCRIPTION
**Pull request by Khalian**
<Type> : feature/test

## Checklist

- [x] New Extension
- [x] New Test
- [ ] Changed more than one extension, but all changes are related
- [ ] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by piv199** [comment]
Does it make any sense? I'm not used to this functions. I can't approve/disapprove this pr :)

**Comment by Khalian** [comment]
@piv199 huh ?

**Comment by piv199** [comment]
How could we get point from angle? Is it logically normal?)

**Comment by Khalian** [comment]
Ah yes, its normal. 

self.init(x: cos(angle), y: sin(angle) will create the point. If you take the length from origin = x^2 + y^2 we get Cos^2 (angle) + Sin^2(angle) which is always 1. 

This extension is effectively a polar coordinate to cartesian transform minus the scaling factor (to keep it simple).

**Comment by Khalian** [comment]
Actually I don;t really mind it being a proper coordinate transform function (that would have a CGFloat scaling factor), but its upto you guys if thats a useful extension?

**Pull request merged**
