### PR TITLE
Added a shuffle function to ArrayExtensions.swift

### PR DESCRIPTION
**Pull request by Daniel-Lopez**
The shuffle function uses the Fisher-Yates-Durstenfeld algorithm.

### CODE REVIEW

**Comment by goktugyil** [comment]
Thanks but there are merge conflicts, mind fixing them?
And why are there 2 versions now?

**Comment by Daniel-Lopez** [comment]
Ok, the conflict is fixed.

The first version was an unproven shuffling algorithm, so I changed it to the well known Fisher-Yates-Durstenfeld algorithm.

**Comment by goktugyil** [comment]
I meant why keep the first version in there?

**Comment by Daniel-Lopez** [comment]
Sorry but I don't understand. There's only one version of shuffle. Are you talking about the shuffle function itself?

**Comment by goktugyil** [comment]
Oh it was my mistake, I though the standard and Fisher method were both in the code.

Thanks for the PR :+1:

**Pull request merged**
