### PR TITLE
Added new extension "navigationBarHidden".

### PR DESCRIPTION
**Pull request by vilapuigvila**
## Checklist

- [x] New Extension
- [x] New Test
- [ ] Changed more than one extension, but all changes are related
- [ ] Trivial change (doesn't require changelog)

### CODE REVIEW

**Comment by lfarah** [comment]
I liked it because ```setNavigationBarHidden``` is not Swifty, so this extension is useful!

**Comment by goktugyil** [comment]
navigationBarHidden is also not very clear cause its requiring a variable after that. I expect this function to return true or false depending on if nav bar is hidden. 

How about, 
hideNavigationBar() 
showNavigationBar()

navigationBarVisibility(_hide: Bool)

?

Also you should get a swiftlint error from 'hide:Bool'

**Comment by vilapuigvila** [comment]
We can do isNavigationBarHidden? like "isHidden", "isUserInteractionEnabled".
What do you think?

**Comment by goktugyil** [comment]
Yeah that might work

**Comment by Khalian** [comment]
@vilapuigvila Would you mind merging these changes and adding a CHANGELOG entry. I will merge it after those steps.

**Comment by Khalian** [comment]
I am performing a manual merge on this (via command line) and maybe use another PR. I will also add a CHANGELOG entry. I do not presume there would be an issue since its approved by two users.

**Comment by Khalian** [comment]
https://github.com/goktugyil/EZSwiftExtensions/pull/428

**Pull request closed without merging**
